// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCiJ2yUWDE4jPxfqAV-MTJuvVfukcUFM',
    appId: '1:4280833659:web:8822ec073122d8e182b4de',
    messagingSenderId: '4280833659',
    projectId: 'quotes-82d0c',
    authDomain: 'quotes-82d0c.firebaseapp.com',
    databaseURL: 'https://quotes-82d0c.firebaseio.com',
    storageBucket: 'quotes-82d0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5BNyvLpbRuaHQfqzf7Ke6q5Y-a06WDAM',
    appId: '1:4280833659:android:59521119cbc09cc082b4de',
    messagingSenderId: '4280833659',
    projectId: 'quotes-82d0c',
    databaseURL: 'https://quotes-82d0c.firebaseio.com',
    storageBucket: 'quotes-82d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrsY2p_etYizsi8Apj_604vsfmYkS03DI',
    appId: '1:4280833659:ios:4e3a623fb29174b882b4de',
    messagingSenderId: '4280833659',
    projectId: 'quotes-82d0c',
    databaseURL: 'https://quotes-82d0c.firebaseio.com',
    storageBucket: 'quotes-82d0c.appspot.com',
    androidClientId: '4280833659-cll3rssii7e0q34deck5eukmjt2q7iop.apps.googleusercontent.com',
    iosClientId: '4280833659-bp9b77ulol2519pgrs2gbfg8m748rql2.apps.googleusercontent.com',
    iosBundleId: 'com.locnga.quotesgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrsY2p_etYizsi8Apj_604vsfmYkS03DI',
    appId: '1:4280833659:ios:4e3a623fb29174b882b4de',
    messagingSenderId: '4280833659',
    projectId: 'quotes-82d0c',
    databaseURL: 'https://quotes-82d0c.firebaseio.com',
    storageBucket: 'quotes-82d0c.appspot.com',
    androidClientId: '4280833659-cll3rssii7e0q34deck5eukmjt2q7iop.apps.googleusercontent.com',
    iosClientId: '4280833659-bp9b77ulol2519pgrs2gbfg8m748rql2.apps.googleusercontent.com',
    iosBundleId: 'com.locnga.quotesgram',
  );
}
